server:
  port: 8181

spring:
  application:
    name: server-service
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false

cloud:
  aws:
    region: eu-west-1

logging:
  level:
    com.spt.k8s.server: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

ping-pong:
  queue:
    name: PingPongMessages-Q